/*
 * Move2Kube API
 * This is a documentation of the Move2Kube REST API. All API calls expect the `Authorization: Bearer <access-token>` HTTP header unless specified otherwise. The access token can be obtained in the same way as OAuth 2.0 using the token endpoint in the admin section. 
 *
 * The version of the OpenAPI document: v1.0.0
 * Contact: move2kube-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.parodos.move2kube.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * GetSupportInfo200Response
 */
@JsonPropertyOrder({
  GetSupportInfo200Response.JSON_PROPERTY_CLI_VERSION,
  GetSupportInfo200Response.JSON_PROPERTY_API_VERSION,
  GetSupportInfo200Response.JSON_PROPERTY_UI_VERSION,
  GetSupportInfo200Response.JSON_PROPERTY_DOCKER
})
@JsonTypeName("get_support_info_200_response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-10-17T12:21:13.081862Z[Etc/UTC]")
public class GetSupportInfo200Response {
  public static final String JSON_PROPERTY_CLI_VERSION = "cli_version";
  private String cliVersion;

  public static final String JSON_PROPERTY_API_VERSION = "api_version";
  private String apiVersion;

  public static final String JSON_PROPERTY_UI_VERSION = "ui_version";
  private String uiVersion;

  public static final String JSON_PROPERTY_DOCKER = "docker";
  private String docker;

  public GetSupportInfo200Response() {
  }

  public GetSupportInfo200Response cliVersion(String cliVersion) {
    
    this.cliVersion = cliVersion;
    return this;
  }

   /**
   * The version, commit hash, etc. of the Move2Kube CLI tool being used.
   * @return cliVersion
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CLI_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCliVersion() {
    return cliVersion;
  }


  @JsonProperty(JSON_PROPERTY_CLI_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCliVersion(String cliVersion) {
    this.cliVersion = cliVersion;
  }


  public GetSupportInfo200Response apiVersion(String apiVersion) {
    
    this.apiVersion = apiVersion;
    return this;
  }

   /**
   * The version, commit hash, etc. of the Move2Kube API server being used.
   * @return apiVersion
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_API_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getApiVersion() {
    return apiVersion;
  }


  @JsonProperty(JSON_PROPERTY_API_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
  }


  public GetSupportInfo200Response uiVersion(String uiVersion) {
    
    this.uiVersion = uiVersion;
    return this;
  }

   /**
   * The version, commit hash, etc. of the Move2Kube UI website being used.
   * @return uiVersion
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UI_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUiVersion() {
    return uiVersion;
  }


  @JsonProperty(JSON_PROPERTY_UI_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUiVersion(String uiVersion) {
    this.uiVersion = uiVersion;
  }


  public GetSupportInfo200Response docker(String docker) {
    
    this.docker = docker;
    return this;
  }

   /**
   * Whether the docker socket &#39;/var/run/docker.sock&#39; is mounted when running as a container.
   * @return docker
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DOCKER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDocker() {
    return docker;
  }


  @JsonProperty(JSON_PROPERTY_DOCKER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDocker(String docker) {
    this.docker = docker;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetSupportInfo200Response getSupportInfo200Response = (GetSupportInfo200Response) o;
    return Objects.equals(this.cliVersion, getSupportInfo200Response.cliVersion) &&
        Objects.equals(this.apiVersion, getSupportInfo200Response.apiVersion) &&
        Objects.equals(this.uiVersion, getSupportInfo200Response.uiVersion) &&
        Objects.equals(this.docker, getSupportInfo200Response.docker);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cliVersion, apiVersion, uiVersion, docker);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetSupportInfo200Response {\n");
    sb.append("    cliVersion: ").append(toIndentedString(cliVersion)).append("\n");
    sb.append("    apiVersion: ").append(toIndentedString(apiVersion)).append("\n");
    sb.append("    uiVersion: ").append(toIndentedString(uiVersion)).append("\n");
    sb.append("    docker: ").append(toIndentedString(docker)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `cli_version` to the URL query string
    if (getCliVersion() != null) {
      try {
        joiner.add(String.format("%scli_version%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCliVersion()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `api_version` to the URL query string
    if (getApiVersion() != null) {
      try {
        joiner.add(String.format("%sapi_version%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getApiVersion()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `ui_version` to the URL query string
    if (getUiVersion() != null) {
      try {
        joiner.add(String.format("%sui_version%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getUiVersion()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `docker` to the URL query string
    if (getDocker() != null) {
      try {
        joiner.add(String.format("%sdocker%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDocker()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}

