/*
 * Move2Kube API
 * This is a documentation of the Move2Kube REST API. All API calls expect the `Authorization: Bearer <access-token>` HTTP header unless specified otherwise. The access token can be obtained in the same way as OAuth 2.0 using the token endpoint in the admin section. 
 *
 * The version of the OpenAPI document: v1.0.0
 * Contact: move2kube-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.parodos.move2kube.api;

import dev.parodos.move2kube.ApiException;
import dev.parodos.move2kube.client.model.CreateWorkspace201Response;
import dev.parodos.move2kube.client.model.Error;
import dev.parodos.move2kube.client.model.Workspace;
import org.junit.Test;
import org.junit.Ignore;
import org.junit.Assert;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WorkspacesApi
 */
@Ignore
public class WorkspacesApiTest {

    private final WorkspacesApi api = new WorkspacesApi();

    /**
     * Create a new workspace. The ID will be generated by the server.
     *
     * Create a new workspace. The ID will be generated by the server.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createWorkspaceTest() throws ApiException {
        Workspace body = null;
        CreateWorkspace201Response response = api.createWorkspace(body);

        // TODO: test validations
    }
    /**
     * Delete an existing workspace.
     *
     * Delete an existing workspace.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteWorkspaceTest() throws ApiException {
        String workspaceId = null;
        api.deleteWorkspace(workspaceId);

        // TODO: test validations
    }
    /**
     * Get the workspace with the given ID.
     *
     * Get the workspace with the given ID.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getWorkspaceTest() throws ApiException {
        String workspaceId = null;
        Workspace response = api.getWorkspace(workspaceId);

        // TODO: test validations
    }
    /**
     * Get all the workspaces you have access to.
     *
     * Get all the workspaces you have access to.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getWorkspacesTest() throws ApiException {
        List<Workspace> response = api.getWorkspaces();

        // TODO: test validations
    }
    /**
     * Update a workspace. The workspace will be created if it doesn&#39;t exist.
     *
     * Update a workspace. The workspace will be created if it doesn&#39;t exist.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateWorkspaceTest() throws ApiException {
        String workspaceId = null;
        Workspace body = null;
        api.updateWorkspace(workspaceId, body);

        // TODO: test validations
    }
}
