/*
 * Move2Kube API
 * This is a documentation of the Move2Kube REST API. All API calls expect the `Authorization: Bearer <access-token>` HTTP header unless specified otherwise. The access token can be obtained in the same way as OAuth 2.0 using the token endpoint in the admin section. 
 *
 * The version of the OpenAPI document: v1.0.0
 * Contact: move2kube-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.parodos.move2kube.api;

import dev.parodos.move2kube.ApiException;
import dev.parodos.move2kube.client.model.CreateWorkspaceInput201Response;
import dev.parodos.move2kube.client.model.Error;
import java.io.File;
import org.junit.Test;
import org.junit.Ignore;
import org.junit.Assert;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WorkspaceInputsApi
 */
@Ignore
public class WorkspaceInputsApiTest {

    private final WorkspaceInputsApi api = new WorkspaceInputsApi();

    /**
     * Create a new input for this workspace. All the projects in this workspace will be able to use it. The ID will be generated by the server.
     *
     * Create a new input for this workspace. All the projects in this workspace will be able to use it. The ID will be generated by the server.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createWorkspaceInputTest() throws ApiException {
        String workspaceId = null;
        String type = null;
        String description = null;
        File _file = null;
        CreateWorkspaceInput201Response response = api.createWorkspaceInput(workspaceId, type, description, _file);

        // TODO: test validations
    }
    /**
     * Delete the input of the project.
     *
     * Delete the input of the project.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteWorkspaceInputTest() throws ApiException {
        String workspaceId = null;
        String inputId = null;
        api.deleteWorkspaceInput(workspaceId, inputId);

        // TODO: test validations
    }
    /**
     * Get the input of the project with the given ID.
     *
     * Get the input of the project with the given ID.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getWorkspaceInputTest() throws ApiException {
        String workspaceId = null;
        String inputId = null;
        File response = api.getWorkspaceInput(workspaceId, inputId);

        // TODO: test validations
    }
}
