/*
 * Move2Kube API
 * This is a documentation of the Move2Kube REST API. All API calls expect the `Authorization: Bearer <access-token>` HTTP header unless specified otherwise. The access token can be obtained in the same way as OAuth 2.0 using the token endpoint in the admin section. 
 *
 * The version of the OpenAPI document: v1.0.0
 * Contact: move2kube-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.parodos.move2kube.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for GetSupportInfo200Response
 */
public class GetSupportInfo200ResponseTest {
    private final GetSupportInfo200Response model = new GetSupportInfo200Response();

    /**
     * Model tests for GetSupportInfo200Response
     */
    @Test
    public void testGetSupportInfo200Response() {
        // TODO: test GetSupportInfo200Response
    }

    /**
     * Test the property 'cliVersion'
     */
    @Test
    public void cliVersionTest() {
        // TODO: test cliVersion
    }

    /**
     * Test the property 'apiVersion'
     */
    @Test
    public void apiVersionTest() {
        // TODO: test apiVersion
    }

    /**
     * Test the property 'uiVersion'
     */
    @Test
    public void uiVersionTest() {
        // TODO: test uiVersion
    }

    /**
     * Test the property 'docker'
     */
    @Test
    public void dockerTest() {
        // TODO: test docker
    }

}
